version: '3'

services:
  v2ray:
    build: ./v2ray
    container_name: v2ray
    restart: always
    ports: 
      - 10000:10000
    volumes:
      - /etc/v2ray/config.json:/etc/v2ray/config.json
    environment:
      - VIRTUAL_HOST=
      - VIRTUAL_PORT=10000
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
    network_mode: "host"
  
  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: "host"

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: "host"
    depends_on:
      - proxy
    
volumes:
  certs:
  vhost.d:
  html: